### ISSUE TITLE
Add Update Pet Not Working

### ISSUE THREAD

**Issue by GetinetA** [GetinetA/jabirinc-pet-clinic#65]
Template errors in Thymeleaf.

Caused by: org.attoparser.ParseException: Error during execution of processor 'org.thymeleaf.spring5.processor.SpringOptionFieldTagProcessor' (template: "fragments/selectField" - line 12, col 13)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393)
	at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230)
	... 64 more
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.spring5.processor.SpringOptionFieldTagProcessor' (template: "fragments/selectField" - line 12, col 13)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:117)
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)

**Comment by GetinetA** [comment]
The issue is the selection element for Pet Type needs a know how to change the selected Pet (which is String) to its corresponding object. Spring uses a Formatter for this. This is similar to Java EE JSF Faces converters.
